[package]
name = "vesmish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
nom-recursive = "0.5.1"
nom_locate = "4.2.0"

[[bin]]
name = "vesmish"

[lib]
