// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "0[QVQPOOOOQO'#C^'#C^O[QPO'#DoOOQO'#Dg'#DgQVQPOOOOQPO,5:ZOOQO-E7e-E7eOaQPO'#CaOiQPO'#CcOnQPO'#DpOsQPO1G/uOOQPO,58}OxQPO'#CgO!QQPO,5:[OOQO'#Df'#DfOOQO7+%a7+%aO!VQPO'#DhO!bQPO1G.iO!gQPO'#DqO!lQPO,59RO!tQPO,59RO!|QPO,59RO#RQPO1G/vOOQO,5:S,5:SOOQO-E7f-E7fOOQO7+$T7+$TO#WQPO,5:]OOQO,5:T,5:TO#]QPO1G.mO#bQPO1G.mOOQO-E7g-E7gO#jQPO1G.mOOQPO'#CoOOQPO'#CnO#oQPO7+%bOOQO1G/w1G/wO#tQPO7+$XO#yQPO7+$XP!oQPO'#DiO$OQPO7+$XOOQO'#Cd'#CdO$TQPO'#CqO$]QPO,59YO$bQQO'#DRO$gQPO<<H|O$OQPO<<GsO$lQPO<<GsOOQPO'#CmOOQO<<Gs<<GsO$qQPO,59]OOQO'#DW'#DWO$vQPO'#DVOOQO'#Dj'#DjO${QPO1G.tO$vQPO,59mO%TQPO'#D_O%YQPOAN>hOOQOAN=_AN=_O$OQPOAN=_O%_QPO,59XOOQPO,59XOOQPO'#CrO%gQPO1G.wO%lQPO'#DUO%qQQO,59qOOQO-E7h-E7hOOQO1G/X1G/XO%yQPO,59yO&UQPO,59yOOQO,59y,59yOOQPO'#D`O&ZQPOG24SOOQOG22yG22yOOQO1G.s1G.sO&`QPO1G.sOOQPO-E7eO&hQQO,59^O'cQPO7+$cOOQO,59p,59pOOQPO1G/]O'hQQO1G/]O'mQPO7+$sOOQO,5:V,5:VOOQO1G/e1G/eO'xQPO1G/eOOQO-E7i-E7iO(TQPO,59zO(]QPO'#DeO(eQPOLD)nOOQO7+$_7+$_OOQPO1G.xO#oQPO<<G}O(jQPO7+$wOOQPO7+$wOOQO7+%P7+%PO(rQPO'#DkO(zQPO1G/fO)PQPO,5:POOQO,5:P,5:PO)XQPO,5:PO)aQPO!$'MYO)fQPO7+$dOOQOAN=iAN=iOOQO'#DZ'#DZOOQO<<Hc<<HcO(jQPO<<HcOOQO7+%Q7+%QO)nQPO1G/kOOQO1G/k1G/kO$OQPO!)9BtOOQO<<HO<<HOOOQOAN=}AN=}OOQO7+%V7+%VO)vQPO7+%VO$qQPO!.K8`OOQO<<Hq<<HqOOQO!4/-z!4/-z",
  stateData: "*O~O!bOS~ORPO~OSTO~OXWX!OTX~OXZO~OX[O~O!O^O~ORbOUeO~ORfO~OYgOU![XXWX~OUiO~O[jO~OUlOYkO~ORbOUlO~O^oO~OdpO~O]sO~O^tO~OUuOYkO~O]wO~O]{O~O]}O~O^!OO~O`!PO~OR!ROX[O~O{!SO~Ov!WO~O!Q!XO~O]![O~OX!_O~O]!aO~O{!SO]bi~O!P!gO~O!T!hO~O_!kOXWX~Os!oO~Ow!pO~OR!rO|!qO~OY!tO!P!uOXWX~O!P!uO~O!W!yO~O_!{OXWX~Og!|Oh!|Oi!|Oj!|Ok!|Ol!|Om!|On!|Oo!|Op!|Oq!|Or!|OXWX~Ot!}O~O|#PO~OXWX!Quq{uq~OY!tO!P#QOXWX~O!U#SOXWX~ORPO!V#UO~Ot#WO~O!O#ZOXWX~OY!tOXWX~OR#^O~O{#_OXWX~ORPO!V#`O~Os#aO~OU#bOXWX~ORPO!V#dO~ORPO!V#gO~O",
  goto: "'j!fPP!gPP!oP!r#XPP#lPPPPP#p#|$PP$S$VPPPPPPPPPPPPPP$]PP$c$i$mPP$qPPP$w$zPPPP$}%Q%T%j%q%w%}PPP&U&c'd]QOS!y#V#_#eRYTpXTZah!P!X!^!_!d!f!h!q!w!y!|#PRyqsWTZahq!P!X!^!_!d!f!h!q!w!y!|#PT]XyQ!QwQ!Z}Q!j![R#f#aRrfRqfRzqQ!`!RR#h#fQ|rR#Y!}Q!b!TR!d!WT!Uz!VT!Tz!VQ#[#OR#c#]R!Y|R!i!YR!z!iR_YQSOUUS#V#eQ!^!PS!m!^!mQ#V!yR#e#_QaZThahQd[RndQ!VzR!c!VQ!f!XT!w!f!w[ROS!y#V#_#eVp!P!^!mQVTU`ZahQxqQ!]!PQ!e!XQ!l!^Q!n!_Q!s!dQ!v!fQ!x!hQ#O!qQ#R!wQ#T!yQ#X!|R#]#PQc[Rmd",
  nodeNames: "⚠ Program LHS Identifier = RHS ) FunctionCall FunctionValue ( , FunctionDef : Type -> } { Block EnumMatching QM ? EnumExpr BinaryOperation +. -. *. /. <. >. + - * / ~~ ~ String Number EnumFull :: Tick EnumVariant EnumBranch Pipe | FatArrow BS ; ] [ List RecordAccess @ . > < Record DS",
  maxTerm: 67,
  nodeProps: [
    ["openedBy", 6,"(",15,"{",47,"[",53,"<"],
    ["closedBy", 9,")",16,"}",48,"]",54,">"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "*o~RnXY#PYZ#P]^#Ppq#Prs#bxy%Oyz%Tz{%Y{|%g|}&b}!O&g!O!P'P!P!Q'U!Q![%w![!]'c!]!^'p!^!_'u!_!`(S!`!a(a!a!b(n!b!c(s!c!}(x!}#O)a#P#Q)f#S#T)k#T#o)p#o#p*R#p#q*W#q#r*]#r#s*b~#US!b~XY#PYZ#P]^#Ppq#P~#eVOr#brs#zs#O#b#O#P$P#P;'S#b;'S;=`$x<%lO#b~$POs~~$SRO;'S#b;'S;=`$];=`O#b~$`WOr#brs#zs#O#b#O#P$P#P;'S#b;'S;=`$x;=`<%l#b<%lO#b~${P;=`<%l#b~%TOX~~%YOU~~%_Po~!O!P%b~%gOi~~%lQmQ!O!P%r!Q![%w~%wOg~P%|QtP!O!P&S!Q![%wP&VP!Q![&YP&_PtP!Q![&Y~&gOY~~&lRnQ!O!P&u!Q![%w!`!a&z~&zOh~P'PO^P~'UO!U~~'ZPp~!O!P'^~'cOj~R'hP[P![!]'kQ'pOvQ~'uO!O~R'zP!WP!O!P'}Q(SOkQR(XPSP!`!a([Q(aO|QR(fP!VP!O!P(iQ(nOlQ~(sOd~~(xO!T~~(}U]~!Q![(x!^!_(x!`!a(x!c!}(x#R#S(x#T#o(x~)fO!Q~~)kO!P~~)pOw~~)uSR~!Q![)p!c!})p#R#S)p#T#o)p~*WO`~~*]O{~~*bO_~~*gPr~#r#s*j~*oOq~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
