// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from "@lezer/lr";
export const parser = LRParser.deserialize({
  version: 14,
  states:
    "0tQVQPOOOOQO'#C^'#C^O[QPO'#DpOOQO'#Dh'#DhQVQPOOOOQPO,5:[OOQO-E7f-E7fOaQPO'#CaOiQPO'#CcOnQPO'#DqOsQPO1G/vOOQPO,58}OxQPO'#CgO!QQPO,5:]OOQO'#Dg'#DgOOQO7+%b7+%bO!VQPO'#DiO!bQPO1G.iO!gQPO'#DrO!lQPO,59RO!tQPO,59RO!|QPO,59RO#RQPO1G/wOOQO,5:T,5:TOOQO-E7g-E7gOOQO7+$T7+$TO#WQPO,5:^OOQO,5:U,5:UO#]QPO1G.mO#bQPO1G.mOOQO-E7h-E7hO#WQPO1G.mOOQPO'#CrOOQPO'#CqO#jQPO7+%cO#oQPO'#CiOOQO1G/x1G/xO#WQPO7+$XO$TQPO7+$XP!oQPO'#DjO$YQPO7+$XOOQO'#Cd'#CdO$_QPO'#CtO$gQPO,59]O$lQQO'#DUO$qQPO<<H}O#WQPO,59TO$YQPO<<GsO#WQPO<<GsOOQPO'#CpOOQO<<Gs<<GsO$vQPO,59`OOQO'#DZ'#DZO#WQPO'#DYOOQO'#Dk'#DkO${QPO1G.wO#WQPO,59pO%TQPO'#DbO%YQPOAN>iO%_QPO1G.oOOQOAN=_AN=_O$YQPOAN=_O%dQPO,59[OOQPO,59[OOQPO'#CuO%lQPO1G.zO%qQPO'#DXO%vQQO,59tOOQO-E7i-E7iOOQO1G/[1G/[O&OQPO,59|O&ZQPO,59|OOQO,59|,59|OOQPO'#DcO&`QPOG24TOOQO7+$Z7+$ZOOQOG22yG22yOOQO1G.v1G.vO&eQPO1G.vOOQPO-E7fO&mQQO,59aO'hQPO7+$fOOQO,59s,59sOOQPO1G/`O'mQQO1G/`O'rQPO7+$vOOQO,5:W,5:WOOQO1G/h1G/hO'}QPO1G/hOOQO-E7j-E7jO(YQPO,59}O(bQPO'#DfO(jQPOLD)oOOQO7+$b7+$bOOQPO1G.{O#jQPO<<HQO(oQPO7+$zOOQPO7+$zOOQO7+%S7+%SO(wQPO'#DlO)PQPO1G/iO)UQPO,5:QOOQO,5:Q,5:QO)^QPO,5:QO)fQPO!$'MZO)kQPO7+$gOOQOAN=lAN=lOOQO'#D^'#D^OOQO<<Hf<<HfO(oQPO<<HfOOQO7+%T7+%TO)sQPO1G/lOOQO1G/l1G/lO$YQPO!)9BuOOQO<<HR<<HROOQOAN>QAN>QOOQO7+%W7+%WO){QPO7+%WO$vQPO!.K8aOOQO<<Hr<<HrOOQO!4/-{!4/-{",
  stateData:
    "*T~O!cOS~ORPO~OSTO~OXWX!RTX~OXZO~OX[O~O!R^O~ORbOUeO~ORfO~OYgOU!]XXWX~OUiO~O[jO~OUlOYkO~ORbOUlO~OaoO~OgpO~O^sO~OauO~OUvOYkO~O^|O~O_!OOU]XY]Xc]X`]Xz]X~Oa!QO~Oc!RO~OR!TOX[O~O!O!UO~Oy!YO~O!T!ZO~OX!bO~O!O!UO^ei~O!S!jO~O!W!kO~O`!mO~Ob!oOXWX~Ov!sO~Oz!tO~OR!vO!P!uO~OY!xO!S!yOXWX~O!S!yO~O_!}O~Ob#POXWX~Oj#QOk#QOl#QOm#QOn#QOo#QOp#QOq#QOr#QOs#QOt#QOu#QOXWX~Ow#RO~O!P#TO~OXWX!Txq!Oxq~OY!xO!S#UOXWX~O!X#WOXWX~ORPO`#YO~Ow#[O~O!R#_OXWX~OY!xOXWX~OR#bO~O!O#cOXWX~ORPO`#dO~Ov#eO~OU#fOXWX~ORPO`#hO~ORPO`#kO~O",
  goto: "(O!gPP!hPP!pP!s#YPP#mP#qPPPPPP$U$b$eP$h$kPPPPPPPPPPPPPP$qPP$w$}%RPP%VPPP%]%`PP%c%f%i&O&V&]&cPPP&j&w'x]QOS!}#Z#c#iRYTpXTZah!R!Z!a!b!g!i!k!u!{!}#Q#TRzqsWTZahq!R!Z!a!b!g!i!k!u!{!}#Q#TT]XzQtjQxoQ!PuQ!]!OQ!_!QT!d!V!YQ!SxQ!^!PQ!n!_R#j#eRrfRqfR{qQ!c!TR#l#jQ}rR#^#RQ!e!VR!g!YT!W{!XT!V{!XQ#`#SR#g#aR![}R!l![R#O!lR_YQSOUUS#Z#iQ!a!RS!q!a!qQ#Z!}R#i#cQaZThahQd[RndQ!X{R!f!XQ!i!ZT!{!i!{[ROS!}#Z#c#iVp!R!a!qQVTU`ZahQyqQ!`!RQ!h!ZQ!p!aQ!r!bQ!w!gQ!z!iQ!|!kQ#S!uQ#V!{Q#X!}Q#]#QR#a#TQc[Rmd",
  nodeNames:
    "⚠ Program LHS Identifier = RHS ) FunctionCall FunctionValue ( , FunctionDef : Type TypeName < > -> } { Block EnumMatching QM ? EnumExpr BinaryOperation +. -. *. /. <. >. + - * / ~~ ~ String Number EnumFull :: Tick EnumVariant EnumBranch Pipe | FatArrow BS ; ] [ List RecordAccess @ . Record DS",
  maxTerm: 68,
  nodeProps: [
    ["openedBy", 6, "(", 16, "<", 18, "{", 50, "["],
    ["closedBy", 9, ")", 15, ">", 19, "}", 51, "]"],
  ],
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData:
    "*i~RnXY#PYZ#P]^#Ppq#Prs#bxy%Oyz%Tz{%Y{|%g|}&b}!O&g!O!P'P!P!Q'U!Q![%w![!]'c!]!^'p!^!_'u!_!`(S!`!a(a!a!b(n!b!c(s!c!}(x!}#O)Z#P#Q)`#S#T)e#T#o)j#o#p){#p#q*Q#q#r*V#r#s*[~#US!c~XY#PYZ#P]^#Ppq#P~#eVOr#brs#zs#O#b#O#P$P#P;'S#b;'S;=`$x<%lO#b~$POv~~$SRO;'S#b;'S;=`$];=`O#b~$`WOr#brs#zs#O#b#O#P$P#P;'S#b;'S;=`$x;=`<%l#b<%lO#b~${P;=`<%l#b~%TOX~~%YOU~~%_Pr~!O!P%b~%gOl~~%lQpQ!O!P%r!Q![%w~%wOj~P%|QwP!O!P&S!Q![%wP&VP!Q![&YP&_PwP!Q![&Y~&gOY~~&lRqQ!O!P&u!Q![%w!`!a&z~&zOk~P'POaP~'UO!X~~'ZPs~!O!P'^~'cOm~R'hP[P![!]'kQ'pOyQ~'uO!R~R'zP_P!O!P'}Q(SOnQR(XPSP!`!a([Q(aO!PQR(fP`P!O!P(iQ(nOoQ~(sOg~~(xO!W~~(}S^~!Q![(x!c!}(x#R#S(x#T#o(x~)`O!T~~)eO!S~~)jOz~~)oSR~!Q![)j!c!})j#R#S)j#T#o)j~*QOc~~*VO!O~~*[Ob~~*aPu~#r#s*d~*iOt~",
  tokenizers: [0, 1],
  topRules: { Program: [0, 1] },
  tokenPrec: 0,
});
